// AUTOGENERATED, DO NOT EDIT.
package types

import (
	"github.com/shadiestgoat/subdb"
)

// Util for int-based fields (uint & int)
type IntBase[T int | uint] struct {
	HelperValue[T]
	// The size of the int in bytes. Valid values are 2 (uint16), 4 (uint32), 8 (uint64)
	Size int
}

func (i IntBase[T]) Encode() []byte {
	return encodeInt[T](i.Value, i.Size)
}

func (i *IntBase[T]) Load(v []byte) {
	i.Value = decodeInt[T](i.Size, v) 
}

func (i IntBase[T]) New() subdb.Field {
	return &IntBase[T]{
		Size:  i.Size,
	}
}

func (i IntBase[T]) StaticSize() int {
	return i.Size
}

type Int struct {
	IntBase[int]
}

type Uint struct {
	IntBase[uint]
}